name: Feature request
description: Suggest an idea for Kindle Bridge
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please avoid including any personal Kindle content or Amazon account details in your description.

  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
